# Basic
title: ThickFive's Den
subtitle: 也许这就是人生吧
welcome_message: 欢迎来到我的秘密星球
description: 我是 ThickFive, 一名 Swift && JavaScript 程序员。

url: "https://onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

blog_button:
    title: 博客
    description: 访问博客

# Pagination
plugins: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"

# Comment
comment:
    disqus: thickfive
    # duoshuo:
# Social
social:
    github: thickfive
    mail: thickfive@live.com

# Google Analytics
ga:
    id: UA-25719337-1
    host: onevcat.com
